create product category
Knawat/dropshipping-woocommerce pull request #135
Opened 2020-09-16 14:22 UTC by DevWael

I have changed the functionality of the importer class to be able to add product categories with it's nested categories #118

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +	class Knawat_Dropshipping_Woocommerce_Importer extends WC_Product_Importer {
Codacy found an issue: [The class Knawat_Dropshipping_Woocommerce_Importer has an overall complexity of 162 which is very high. The configured complexity threshold is 50.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +					$categories                 = array();
Codacy found an issue: [Avoid unused local variables such as '$categories'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		protected function set_variation_data( &$variation, $data ) {
Codacy found an issue: [The method set_variation_data() has a Cyclomatic Complexity of 14. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		function attribute_languagfy( $lang_object ) {
Codacy found an issue: [The method attribute_languagfy() has a Cyclomatic Complexity of 15. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +			$z                   = 1;
Codacy found an issue: [Avoid unused local variables such as '$z'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		function get_existing_attribute_values( $product_id, $attribute_name ) {
Codacy found an issue: [The method get_existing_attribute_values() has a Cyclomatic Complexity of 17. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +	include_once dirname( WC_PLUGIN_FILE ) . '/includes/import/abstract-wc-product-importer.php';
Codacy found an issue: [The use of function dirname() is discouraged](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:27 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +				knawat_dropshipwc_logger( '[GET_PRODUCTS_FROM_API_ERROR] ' . $api_url . ' ' . print_r( $this->data, true ) );
Codacy found an issue: [The use of function print_r() is discouraged](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		public function import() {
Codacy found an issue: [The method import() has an NPath complexity of 1140864. The configured NPath complexity threshold is 200.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +						foreach ( $variations as $vindex => $variation ) {
Codacy found an issue: [Avoid unused local variables such as '$vindex'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		public function import() {
Codacy found an issue: [The method import() has 161 lines of code. Current threshold is set to 100. Avoid really long methods.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		public function get_formatted_product( $product ) {
Codacy found an issue: [The method get_formatted_product() has a Cyclomatic Complexity of 62. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		public function get_formatted_product( $product ) {
Codacy found an issue: [The method get_formatted_product() has an NPath complexity of 16949578200. The configured NPath complexity threshold is 200.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +			$z                   = 1;
Codacy found an issue: [Avoid variables with short names like $z. Configured minimum length is 3.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +			$cat                 = $new_terms = array();
Codacy found an issue: [Avoid unused local variables such as '$cat'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +	include_once dirname( WC_PLUGIN_FILE ) . '/includes/import/abstract-wc-product-importer.php';
Codacy found an issue: ["include_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		function attribute_languagfy( $lang_object ) {
Codacy found an issue: [The method attribute_languagfy() has an NPath complexity of 1440. The configured NPath complexity threshold is 200.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		public function import() {
Codacy found an issue: [The method import() has a Cyclomatic Complexity of 41. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		protected function set_variation_data( &$variation, $data ) {
Codacy found an issue: [The method set_variation_data() has an NPath complexity of 588. The configured NPath complexity threshold is 200.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 14:28 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +		public function get_formatted_product( $product ) {
Codacy found an issue: [The method get_formatted_product() has 189 lines of code. Current threshold is set to 100. Avoid really long methods.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on templates/admin/dropshipping-woocommerce-settings.php
> +						echo $mp_consumer_key;
Codacy found an issue: [Use of echo language construct is discouraged.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on templates/admin/dropshipping-woocommerce-settings.php
> +						_e( 'Select yes to fetch product categories', 'dropshipping-woocommerce' );
Codacy found an issue: [All output should be run through an escaping function (like esc_html_e() or esc_attr_e()), found '_e'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on templates/admin/dropshipping-woocommerce-settings.php
> +						echo $mp_consumer_secret;
Codacy found an issue: [Use of echo language construct is discouraged.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on templates/admin/dropshipping-woocommerce-settings.php
> +	exit;
Codacy found an issue: [Use of exit language construct is discouraged.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on templates/admin/dropshipping-woocommerce-settings.php
> +						echo $mp_consumer_secret;
Codacy found an issue: [All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$mp_consumer_secret'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-common.php
> +	exit;
Codacy found an issue: [Use of exit language construct is discouraged.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on templates/admin/dropshipping-woocommerce-settings.php
> +					<?php _e( 'Categorize Products', 'dropshipping-woocommerce' ); ?>
Codacy found an issue: [All output should be run through an escaping function (like esc_html_e() or esc_attr_e()), found '_e'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-16 15:29 UTC, HazemKhaled commented on templates/admin/dropshipping-woocommerce-settings.php
> +						echo $mp_consumer_key;
Codacy found an issue: [All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$mp_consumer_key'.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6189509)

2020-09-29 14:05 UTC, hamusthekiller requested changes
Please check the comments I left and try to modify it.
Thank You.

2020-10-13 15:46 UTC, HazemKhaled approved these changes

2020-10-13 15:46 UTC, merged