ADD: Force Update for single and list product/s close #25
Knawat/dropshipping-woocommerce pull request #140
Opened 2020-10-14 13:47 UTC by hamusthekiller

Description:
Added a part where the user can update a single product in the edit product page using the Knawat button for updating.
Also, added a part where the user can select multiple products from the products list in Woocommerce and select Knawat Update from the bulk actions list and the products will be updated.

Steps to test this issue:
1- Download Xampp or any localhost server hosting on your local machine.
2- Download and install WordPress, Woocommerce, qtranslate-x, and all other important plugins that Woocommerce needs to work as expected.
3- Download Knawat Dropshipping plugin and also download recommended plugins by Knawat.
4- Import products into your store.
5- Go to the edit product page in any Knawat product and try to change its values then press update and you should see all these changes reverted to Knawat's original status and updating quantity and price if there is a change in them.
6- Go to all products page and select Knawat Update from bulk actions select box and click apply after that watch the magic happens.
Note: Update Multiple products in the products list might slow down your website speed so don't do it unless 100% sure. Or you can use Knawat dropshipping Plugin to update all products and not slow down Your store.

2020-10-14 15:39 UTC, HazemKhaled commented on templates/products/edit-product.php
> +            if (!isset($_GET['product-update'])){
Codacy found an issue: [Processing form data without nonce verification.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6339143)

2020-10-14 15:39 UTC, HazemKhaled commented on templates/products/edit-product.php
> +    function knawatproduct_metabox(){
Codacy found an issue: [knawatproduct_metabox accesses the super-global variable $_GET.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6339143)

2020-10-14 15:39 UTC, HazemKhaled commented on templates/products/edit-product.php
> +        if (isset($_GET['knawat-update']) && $_GET['knawat-update'] == true){
Codacy found an issue: [Direct use of $_GET Superglobal detected.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6339143)

2020-10-14 15:39 UTC, HazemKhaled commented on templates/products/edit-product.php
> +            if (!isset($_GET['product-update'])){
Codacy found an issue: [Direct use of $_GET Superglobal detected.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6339143)

2020-10-14 15:39 UTC, HazemKhaled commented on templates/products/edit-product.php
> +        if (isset($_GET['knawat-update']) && $_GET['knawat-update'] == true){
Codacy found an issue: [Processing form data without nonce verification.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6339143)

2020-10-19 18:36 UTC, HazemKhaled requested changes

2020-10-19 18:36 UTC, HazemKhaled commented on templates/products/edit-product.php
> +                $knawat_dropshipwc->common->knawat_dropshipwc_before_single_product();
I believe there is better than this in WordPress! please advice @iamdharmesh

2020-10-20 07:22 UTC, iamdharmesh commented on templates/products/edit-product.php
> +                $knawat_dropshipwc->common->knawat_dropshipwc_before_single_product();
@hamusthekiller please don't mix js with PHP. you can do this with 2 ways. choose one of these 2.
1. **Use Ajax** 
2. **Use Post Action with nonce**, like we have done it to trigger sync for sync-failed order. https://github.com/Knawat/dropshipping-woocommerce/blob/master/includes/class-dropshipping-wc-mp-orders.php#L365

2020-11-03 06:58 UTC, iamdharmesh requested changes

2020-11-03 06:58 UTC, iamdharmesh commented on includes/class-dropshipping-wc-async-request.php
> +			$updated = $knawat_dropshipwc->common->knawat_dropshipwc_import_product_by_sku( $sku , true );
Please use force_update optionally, we are also importing product on single product page and before add on cart. so default force_update is not a good way.

2020-11-03 06:58 UTC, iamdharmesh commented on templates/products/edit-product.php
> +            <p>Warning: any changes made to the product will be overwritten</p>
Please Use `_e` or `__` for support text localization/Internationalizatio. follow same for other texts as well.

2020-11-06 13:34 UTC, iamdharmesh commented
closing this  as new PR is created https://github.com/Knawat/dropshipping-woocommerce/pull/153

2020-11-06 13:34 UTC, closed without merging