Add sync bar and button close#137
Knawat/dropshipping-woocommerce pull request #141
Opened 2020-10-14 14:34 UTC by hamusthekiller

Added A sync bar and a sync reset button and here are some screenshots as per the acceptance criteria.
![95831839-3a2d9300-0d42-11eb-985e-cc95f30d721d](https://user-images.githubusercontent.com/26527473/96003901-68df6280-0e43-11eb-9338-27714be127a2.png)
![95831892-4c0f3600-0d42-11eb-9af1-e223a7097e5d](https://user-images.githubusercontent.com/26527473/96003914-6bda5300-0e43-11eb-8af2-bcb44bc2fc9e.png)
![95831773-24b86900-0d42-11eb-8e14-a376720b23fa](https://user-images.githubusercontent.com/26527473/96003926-6f6dda00-0e43-11eb-8ee5-6c067da4fc0a.png)

2020-10-14 15:12 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-common.php
> +		if ( isset( $_POST['knawatds_reset_action']) && $_POST['knawatds_reset_action'] == 'knawatds_reset_sync' ) {
Codacy found an issue: [Direct use of $_POST Superglobal detected.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6339142)

2020-11-03 13:02 UTC, iamdharmesh requested changes

2020-11-03 13:02 UTC, iamdharmesh commented on templates/admin/dropshipping-woocommerce-settings.php
> +			<form method="post" id="knawatds_reset_form">
Better to use admin post action with nonce url instead of form. it will help with handle it separately from setting form submit.

2020-11-30 11:26 UTC, iamdharmesh commented on includes/class-dropshipping-woocommerce-common.php
> +	$data = $mp_api->get('catalog/products?limit=10&page=1&hideOutOfStock=1&lastupdate=' . $timestamp);
Please use count API here. as we already have count API now.

2020-12-02 13:33 UTC, suraj-rathod commented
Fix the sync bar functionality in https://github.com/Knawat/dropshipping-woocommerce/pull/160

2020-12-02 13:33 UTC, closed without merging