Add an option to import categories as tags
Knawat/dropshipping-woocommerce pull request #143
Opened 2020-10-14 18:09 UTC by hamusthekiller

ADD: Added option to import categories as tags or not in the admin settings page.
FIX: Fix in importer according to the above logic

2020-10-19 18:37 UTC, HazemKhaled requested changes

2020-10-19 18:37 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-common.php
> +				if ( $knawatds_options['tagging_products'] == 'yes' ) {
can't we have true & false, or at least 0 & 1

2020-11-03 13:42 UTC, iamdharmesh commented
This PR adds another dropdown which make confusions to users. better to utilize current dropdown to facilitate this. 

![image](https://user-images.githubusercontent.com/10613171/97992310-85e6d000-1e08-11eb-8fbf-3f58355f0c34.png)

2020-11-30 11:10 UTC, suraj-rathod commented
Fix the changes with existing created PR https://github.com/Knawat/dropshipping-woocommerce/pull/157

2020-11-30 11:10 UTC, closed without merging