Performance Optimization in Get Orders and Hotfix for Full Import
Knawat/dropshipping-woocommerce pull request #144
Opened 2020-10-15 08:20 UTC by hamusthekiller

FIX: Optimize Performance in Get Order. Reduce Complexity when getting orders Algorithm.
FIX: Side Case in Full Import Process where it creates wrong product type in products with only 1 variation.

2020-10-15 08:22 UTC, HazemKhaled commented on includes/class-dropshipping-wc-mp-orders.php
> +		$item_whitelist_fields_flipped = array_flip($item_whitelist_fields);
Codacy found an issue: [Avoid excessively long variable names like $item_whitelist_fields_flipped. Keep variable name length under 20.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6343423)

2020-10-15 08:22 UTC, HazemKhaled commented on includes/class-dropshipping-wc-mp-orders.php
> +		$order_whitelist_fields_flipped = array_flip($order_whitelist_fields);
Codacy found an issue: [Avoid excessively long variable names like $order_whitelist_fields_flipped. Keep variable name length under 20.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6343423)

2020-10-15 08:53 UTC, HazemKhaled commented on includes/class-dropshipping-wc-mp-orders.php
> +		$order_whitelist_flipped = array_flip($order_whitelist_fields);
Codacy found an issue: [Avoid excessively long variable names like $order_whitelist_flipped. Keep variable name length under 20.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6343423)

2020-10-15 08:53 UTC, HazemKhaled commented on includes/class-dropshipping-wc-mp-orders.php
> +		$item_whitelist_flipped = array_flip($item_whitelist_fields);
Codacy found an issue: [Avoid excessively long variable names like $item_whitelist_flipped. Keep variable name length under 20.](https://app.codacy.com/gh/Knawat/dropshipping-woocommerce/pullRequest?prid=6343423)

2020-10-19 18:33 UTC, HazemKhaled requested changes

2020-10-19 18:33 UTC, HazemKhaled commented on includes/class-dropshipping-woocommerce-importer.php
> +				if ( isset( $product->variations ) && ! empty( $product->variations ) && ($product->sku != $product->variations[0]->sku)) {
Do we have variations without SKU? would you please explain more about it?

2020-10-22 09:09 UTC, hamusthekiller commented on includes/class-dropshipping-woocommerce-importer.php
> +				if ( isset( $product->variations ) && ! empty( $product->variations ) && ($product->sku != $product->variations[0]->sku)) {
This case happens when a product has only 1 variation and both of the main SKU and the variation SKU are the same which makes them a variable product instead of simple.

2020-11-03 09:29 UTC, iamdharmesh requested changes

2020-11-03 09:29 UTC, iamdharmesh commented on includes/class-dropshipping-woocommerce-importer.php
> +				if ( isset( $product->variations ) && ! empty( $product->variations ) && ($product->sku != $product->variations[0]->sku)) {
I think we have cases where product has multiple variations and one of variation sku is same as product sku, and it could be first variation also.

2020-12-01 10:44 UTC, iamdharmesh commented on includes/class-dropshipping-woocommerce-importer.php
> +				if ( isset( $product->variations ) && ! empty( $product->variations ) && ($product->sku != $product->variations[0]->sku)) {
@HazemKhaled I think we can ignore this. because at knawat all products are variable. even product with 1 variation is variable product so, lets keep it importing as a variable product instead of simple.

@suraj-rathod please remove this line and continue checking with other improvements in this PR.

2020-12-01 13:31 UTC, suraj-rathod commented on includes/class-dropshipping-woocommerce-importer.php
> +				if ( isset( $product->variations ) && ! empty( $product->variations ) && ($product->sku != $product->variations[0]->sku)) {
@iamdharmesh implemented the other changes with the new PR https://github.com/Knawat/dropshipping-woocommerce/pull/159

2020-12-01 13:47 UTC, iamdharmesh commented
closing this as this is already done in https://github.com/Knawat/dropshipping-woocommerce/pull/159

2020-12-01 13:47 UTC, closed without merging