handle states where the property _knawat_cost does not has value e.g:…
Knawat/dropshipping-woocommerce pull request #148
Opened 2020-10-20 22:01 UTC by YasienDwieb

… non-knawat products

2020-10-21 07:40 UTC, hamusthekiller requested changes

2020-10-21 07:40 UTC, hamusthekiller commented on includes/class-dropshipping-woocommerce-orders.php
> +                }
Please, change the linting of the code to be the same as the previous so it can be more readable.

2020-10-21 13:59 UTC, YasienDwieb commented on includes/class-dropshipping-woocommerce-orders.php
> +                }
Okay, I will do that

2020-10-23 21:28 UTC, YasienDwieb commented on includes/class-dropshipping-woocommerce-orders.php
> +                }
Linting on local version is correct and cloning the repo gives a correct linting too
![Uploading Screen Shot 2020-10-23 at 11.21.49 PM.png…]()

2020-10-27 18:18 UTC, hamusthekiller approved these changes

2020-10-30 14:01 UTC, iamdharmesh approved these changes

2020-11-02 13:26 UTC, merged