define $api_url variable so it can be safely referenced
Knawat/dropshipping-woocommerce pull request #149
Opened 2020-10-20 22:27 UTC by YasienDwieb

2020-10-21 07:33 UTC, hamusthekiller requested changes

2020-10-21 07:33 UTC, hamusthekiller commented on includes/class-dropshipping-woocommerce-importer.php
> +					$tag = '';
Please check this link for more info on why We should use unset instead of just nulling any variable in PHP.
https://stackoverflow.com/questions/584960/whats-better-at-freeing-memory-with-php-unset-or-var-null/585205

2020-10-21 07:33 UTC, hamusthekiller commented on includes/class-dropshipping-woocommerce-importer.php
> +					$tag = '';
Same as the above comment.

2020-10-21 13:56 UTC, YasienDwieb commented on includes/class-dropshipping-woocommerce-importer.php
> +					$tag = '';
The process done here is unsetting the variable so it's no more available for concatenation which occurs in later foreach rounds.

This causes undefined $tag variable issues which floods the log.
In case you wish to keep using unset, you would have to redefine it within foreach

2020-10-22 08:54 UTC, hamusthekiller requested changes

2020-10-22 08:54 UTC, hamusthekiller commented on includes/class-dropshipping-woocommerce-importer.php
> +			$api_url = '';
Can You explain why did You add this variable and what is it used for?

2020-10-22 08:54 UTC, hamusthekiller commented on includes/class-dropshipping-woocommerce-importer.php
> +					$tag = '';
Can You tell me how to generate this case? I tried to generate the case but there weren't any logs shown regarding this variable.

2020-10-22 11:37 UTC, YasienDwieb commented on includes/class-dropshipping-woocommerce-importer.php
> +			$api_url = '';
In this function we have a switch case, that only defines $api_url if we matched the 'full' case. This causes errors in later calls that fires ```undefined $api_url``` error when we the case matches other values.

2020-10-22 14:10 UTC, hamusthekiller commented on includes/class-dropshipping-woocommerce-importer.php
> +			$api_url = '';
Can You tell me how to generate this case? Also, should I open php_errors or this error outputs in the logs?

2020-11-03 09:55 UTC, iamdharmesh approved these changes

2020-11-03 09:55 UTC, merged