replace get_coupon_codes with get_coupon_codes due to deprecation
Knawat/dropshipping-woocommerce pull request #150
Opened 2020-10-20 22:51 UTC by YasienDwieb

2020-10-21 05:25 UTC, iamdharmesh requested changes

2020-10-21 05:25 UTC, iamdharmesh commented on includes/class-dropshipping-woocommerce-orders.php
> +        $used_coupons = $parent_order->get_coupon_codes();
Please keep supporting old versions as well. like 
```
if(WC version less than 3.7){
    $used_coupons = $parent_order->get_used_coupons();
}else{
    $used_coupons = $parent_order->get_coupon_codes();
}
```

2020-10-21 13:57 UTC, YasienDwieb commented on includes/class-dropshipping-woocommerce-orders.php
> +        $used_coupons = $parent_order->get_coupon_codes();
Yes, you are absolutely correct. I will do that.
Thanks

2020-10-22 13:42 UTC, iamdharmesh approved these changes

2020-10-22 13:51 UTC, hamusthekiller approved these changes

2020-10-23 21:45 UTC, YasienDwieb commented on includes/class-dropshipping-woocommerce-orders.php
> +        $used_coupons = $parent_order->get_coupon_codes();
Done, please check again.

2020-11-02 13:02 UTC, iamdharmesh commented on includes/class-dropshipping-woocommerce-orders.php
> +        $used_coupons = $parent_order->get_coupon_codes();
Thanks a lot YasienDwieb.

2020-11-02 13:02 UTC, merged