Fix: categories import issue
Knawat/dropshipping-woocommerce pull request #151
Opened 2020-10-28 14:26 UTC by hamusthekiller

There is a normal case where wp_set_post_terms doesn't work as expected so, We should return to wp_set_object_terms as per this PR.

2020-11-03 12:57 UTC, iamdharmesh requested changes

2020-11-03 12:57 UTC, iamdharmesh commented on includes/class-dropshipping-woocommerce-importer.php
> +								$cat_id   = wp_set_object_terms( ! empty( $new_product['id'] ) ? $new_product['id'] : 0, $term_obj->slug, 'product_cat', true );
`wp_set_post_terms` is calling `wp_set_object_terms` internally. it has just few more checks. why we are switching to `wp_set_object_terms`? what issue we are facing with it `wp_set_post_terms`?

2020-11-24 10:43 UTC, suraj-rathod commented on includes/class-dropshipping-woocommerce-importer.php
> +								$cat_id   = wp_set_object_terms( ! empty( $new_product['id'] ) ? $new_product['id'] : 0, $term_obj->slug, 'product_cat', true );
Import category is not working here so need to re-verify it

2020-11-27 10:11 UTC, suraj-rathod commented
Import category and tags have an issue while import time and on update time it's working

2020-11-27 10:11 UTC, closed without merging

2020-11-27 13:29 UTC, iamdharmesh commented
Closed as new PR created for fix https://github.com/Knawat/dropshipping-woocommerce/pull/157