Add support for qTranslate XT plugin as a WordPress multilingual plugin instead of the legacy qTranslate X
Knawat/dropshipping-woocommerce pull request #169
Opened 2020-12-16 09:14 UTC by DevWael

## :memo: Description
The qTranslate-XT plugin is an eXTended version of qTranslate-X that reviving with a new community since the original plugin is abandoned by its author.
i have added the support for qtranslate-xt in the importer class. to be able to import multilingual products with qtranslate-xt

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a migration update

### :scroll: Steps to test
1. install qTranslate XT from https://github.com/qtranslate/qtranslate-xt/archive/3.9.1.zip.
2. set your languages
3. start product syncing.

2020-12-23 10:12 UTC, HazemKhaled requested changes

2020-12-23 10:12 UTC, HazemKhaled commented on includes/knawat-required-plugins.php
> +	$plugins[] = array( //add q-translate-xt in recommended plugins
If we going to use XT, so no need to ask user to download both, let's deprecate qtranslate-x and only have XT

We also need to show oneclick for users to disable the X, download XT and activate it .. as I know no migration required, isn't it?

2020-12-23 10:12 UTC, HazemKhaled commented
FYI @DevWael we also working on #154

2020-12-30 09:19 UTC, merged

2021-01-10 11:36 UTC, HazemKhaled commented
I was trying auto-merge here, and it's merged by mistake, please fix my notes in another PR @suraj-rathod

2021-01-11 12:37 UTC, iamdharmesh commented on includes/knawat-required-plugins.php
> +	$plugins[] = array( //add q-translate-xt in recommended plugins
> We also need to show oneclick for users to disable the X, download XT and activate it .. as I know no migration required, isn't it?
@HazemKhaled do we need to migrate to existing X users to XT? I think we can show conditional recommendation to user to install XT if they are not using X. what do you think?

2021-01-12 09:15 UTC, HazemKhaled commented on includes/knawat-required-plugins.php
> +	$plugins[] = array( //add q-translate-xt in recommended plugins
agree 👍