Update README.txt
Knawat/dropshipping-woocommerce pull request #188
Opened 2021-03-22 12:12 UTC by HeshamIsmail

## :memo: Description

Our copywriting team has created an introductory page for the WooCommerce Dropshipping Plugin page that should be added as soon as possible.

You may find the page in the link below:

https://docs.google.com/document/d/1Q5MhImAStKRYqgeGprAUSabCiLT0IdmBTkWkWNrZzXw/edit### :dart: Relevant issues

### :gem: Type of change

- Plug-in Description modifications

2021-03-23 12:19 UTC, HazemKhaled requested changes

2021-03-23 12:19 UTC, HazemKhaled commented on README.txt
> +=== Description Page ===
required by wordpress.org to be == not. ===

2021-03-23 12:19 UTC, HazemKhaled commented on README.txt
> +Knawat - WooCommerce Dropshipping
why not title?
===Knawat - WooCommerce Dropshipping===

2021-03-23 12:19 UTC, HazemKhaled commented on README.txt
> +=== Features ===
keep it == instead of ===

2021-04-01 11:51 UTC, HeshamIsmail commented on README.txt
> +=== Description Page ===
Updated upon your request

2021-04-01 11:51 UTC, HeshamIsmail commented on README.txt
> +Knawat - WooCommerce Dropshipping
Updated upon your request

2021-04-01 11:51 UTC, HeshamIsmail commented on README.txt
> +=== Features ===
Updated upon your request

2021-04-04 16:05 UTC, merged